        self.writeVInt(0) # за какую валюту будет покупаться(0-гемы, 1-золото, 3-старпоинты)
        self.writeVInt(0) # сколько стоит
        self.writeVInt(0) # время (незн лол)
        self.writeVInt(0)
        self.writeVInt(0)
        self.writeVInt(0)
        self.writeBoolean(False)
        self.writeVInt(0)
        self.writeVInt(0)
        self.writeBoolean(False) # дайли оффер (лол нет как бравлера в дайли можно поставить)
        self.writeVInt(0) # старая цена (0-нету)
        self.writeString("КЛАНСИ") # название акции
        self.writeVInt(0)
        self.writeBoolean(False)
        self.writeString("offer_bgr_deepsea") # код фона акции
        self.writeVInt(0)
        self.writeBoolean(False) # эта покупка уже происходит (тоесть никак не купить вроде)
        self.writeVInt(0) # тип бенефита
        self.writeVInt(0) # бенефит
        self.writeString()
        self.writeBoolean(False) # акция 1 раз
        self.writeBoolean(True) # есть ли она у игрока
        self.writeDataReference(0)
        self.writeDataReference(0)
        self.writeBoolean(False)
        self.writeBoolean(False)
        self.writeBoolean(False)
        self.writeVInt(0)
        self.writeVInt(0)
        self.writeVInt(0)
        self.writeBoolean(False)
        self.writeBoolean(False)
        self.writeVInt(0)
        self.writeVInt(0)
        self.writeBoolean(False)
        self.writeVInt(0)
        self.writeVInt(0)
        self.writeVInt(0)
        self.writeVInt(0)
        self.writeVInt(0)
        self.writeBoolean(False)
        self.writeBoolean(False)
        self.writeBoolean(False)
